# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tags.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntags.proto\"\x1c\n\x0cImageRequest\x12\x0c\n\x04\x66ile\x18\x01 \x01(\x0c\"\x19\n\tTagsReply\x12\x0c\n\x04tags\x18\x01 \x03(\t2.\n\x04Tags\x12&\n\x07getTags\x12\r.ImageRequest\x1a\n.TagsReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tags_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMAGEREQUEST._serialized_start=14
  _IMAGEREQUEST._serialized_end=42
  _TAGSREPLY._serialized_start=44
  _TAGSREPLY._serialized_end=69
  _TAGS._serialized_start=71
  _TAGS._serialized_end=117
# @@protoc_insertion_point(module_scope)
